name: Artifact Demo

on:
  workflow_dispatch:

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Create a report
        run: |
          echo "GitHub Actions learning lesson" > Report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: learning-report
          path: Report.txt

  read_file:
    runs-on: ubuntu-latest
    needs: create_file

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: learning-report

      - name: Read the file
        run: |
          cat Report.txt
