name: NodeJS Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18, 20, 22]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Summary
        run: |
          node --version
          echo "Testing successful on Node.js ${{ matrix.node_version }}"
